---
title: "About"
format: html
---

# AVICHAL WARKE

Junior Research Fellow Contact: (+91) 7304869878 Centre for Political Studies warkeavichal\@gmail.com School of Social Sciences New Delhi - 110067 Jawaharlal Nehru University (JNU) India

Avichal Warke, a recipient of the UGC NET-JRF, March 2022, is a dedicated scholar currently pursuing a PhD in Political Studies at Jawaharlal Nehru University, New Delhi. With a keen focus on the intersection of technology, society, and caste dynamics, he is delving into the complexities of "Social Networking Platforms and Caste Question" for his doctoral research.

He has actively engaged in various academic pursuits, including participation in the 'Digital & Society' Social Sciences Winter School of Pondicherry, “Vajrasuchi” focusing on anti-caste theories and ideology by Sambhavna Institute Himachal, showcasing his commitment to understanding societal complexities. Additionally, he has completed a UGC-sponsored short- term Certificate course in Heritage and Cultural Studies, emphasizing his dedication to holistic learning and advocacy for social justice.

## EDUCATION

PhD in Political Studies 2022-Present • Jawaharlal Nehru University, New Delhi • Working on “Social Networking Platforms and Caste Question”

Masters in Political Science 2019-2021 • Rashtrasant Tukadoji Maharaj Nagpur University, Maharashtra • CGPA: 7.38 (68.75%) Bachelor of Arts 2017-2019 • Hislop College, Nagpur, Maharashtra • (72.07%) Intermediate in Science 2013-2015 • St. Francis De Sales, Junior College, Seminary Hills, Nagpur, Maharashtra • (60.31%) Matriculation 2012-2013 • St. Francis De Sales, High School, Residential Road, Nagpur, Maharashtra • (88.18%)

## ACADEMIC ACTIVITIES / ACHIEVEMENTS

Academic Positions • Selected for PhD programme at the Centre for Political Studies in JNU from the academic session of 2022. • Selected for PhD programme in Political Science at Hyderabad Central University in 2022. • Successfully cleared UGC NET-JRF examination with 97.49 percentile marks in March 2022.

### Academic Activities

• Panelist in the Round Table Discussion in the 11th Creative Theory Colloquium, organized by…… in collaboration with Herbert Marcuse Society USA titled Technology and Society, Sept 2024. • Successfully completed workshop on “Reproducible Research Using R” organized by SARA Institute of Data Science, Sonipat, Haryana, 22-26 July, 2024. • Successfully completed “Vajrasuchi” workshop focusing on anti-caste theories and ideology by Sambhavna Institute, Himachal Pradesh, 10-14 June, 2024. • Successfully completed workshop on 'Digital & Society' Social Sciences Winter School of Pondicherry, organized by Pondicherry University and French Institute of Pondicherry, 13-17 Nov, 2023. • Panelist of the student’s seminar on “Indo-China Border Dispute”. • Successfully completed UGC sponsored short term Certificate course in Heritage and Cultural studies. • Completed workshop on “Human Values – Rights and Opportunities”. • Chatgpt and ai workshop tools bet10x

## SKILLS

R Language- Beginner. RStudio. Academic Writing. Critical Thinking. Literature Review. Report Writing. Articles. Commentaries. MS PowerPoint.\
MS Word. MS Excel.

## LANGUAGES KNOWN

English Hindi Marathi Full Proficiency Proficient Native

## EXTRA CURRICULAR ACTIVITIES

• Represented my High school in State level Shalay Football Tournament (2012-13) • Represented my High school in Divisional level Football Tournament Winner (2012-13) Runners up (2011-12) • Represented my High school in District level Football Tournament Winner (2012-13) Runners up (2011-12) • Successfully represented my undergrad college and won various intercollegiate Dance competitions.

## COMMUNITY LEADERSHIP

Organized a lecture on “Reproducible Research Made Easy: A live coding session for Social Scientists” by SARA Institute of Data Science for students from marginalized communities in Jawaharlal Nehru University, New Delhi. • Worked as a core committee member in 11th Creative Theory Colloquium, 2024 in collaboration with Herbert Marcuse Society, USA • Served as Vice President of “The Athenaeum” which was the literary and cultural body of my undergrad college. • Served as a mentor for economics to undergrad students of Hislop College. • Attended International Buddhist Youth Convention (IBYC) retreat themed ‘Rise Up & Reach Out’. • Cc of bapsa and election

## PUBLICATIONS

• Who Speaks for whom? The stories of caste, media and representation from behind the curtain, 15 Feb 2024, TheDaak.

https://thedaak.in/2024/02/15/who-speaks-for-whom-the-stories-of-caste-media-and-representation-from-behind-the-curtains. •

Casteist Slurs on JNU Walls: The Deep-Rooted Casteism in Indian Universities, 24 July 2024, TheWire https://thewire.in/caste/casteist-slurs-on-jnu-walls-the-deep-rooted-casteism-in-indian-universities
